services:
  dedicated-server:
    image: kagurazakanyaa/soulmask:latest
    # build: # only use in test
    #   context: .
    restart: unless-stopped
    stop_grace_period: 60s
    network_mode: bridge
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
      # - 18888:18888/tcp # only use if want managed by telnet
    environment:
      - FORCE_UPDATE=false
      # - LEVEL_NAME=Level01_Main # do not change this
      - GAME_PORT=7777
      - QUERY_PORT=27015
      - ECHO_PORT=18888
      - MAX_PLAYERS=20
      - SERVER_NAME=Soulmask Server
      - SAVED_DIR_SUFFIX=
      - SERVER_PASSWORD=
      - ADMIN_PASSWORD=changeme
      - INIT_BACKUP=true
      - BACKUP_INTERVAL_MINUTES=30
      - SAVING_SYNC_INTERVAL_SECONDS=120
      - BACKUP_SYNC_INTERVAL_SECONDS=120
      - GAME_MODE=pve
      - MOD_ID_LIST=
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/opt/soulmask/WS/Saved
